### ISSUE TITLE
Longpoll transport doesn't appear to honor request_timeout parameter

### ISSUE THREAD

**Issue by azazel75** [crossbario/crossbar#1087]
Hello, 

i'm using crossbar in a web application that usually is configured to use websocket transport. Recently a client suffered of connection problems to the websocket transport endpoint caused by its company proxy configurations. While I try to better understand how to resolve this issue I tried to setup a workaround using longpoll transport. After battling with timeouts on the nginx proxy in front of the crossbar instance I stumbled upon an issue that seems caused by the crossbar server itself.

I set up the autobahn-js connection with 60 seconds (60000) request timeout to not have it interfere with the /lp/<session_id>/receive POST and  and configured the transport in crossbar with the following parameters:

```yaml
transports:
  - type: web
    endpoint:
      type: tcp
      port: 8082
    paths:
      /:
        type: static
        directory: /srv/app/www
      lp:
        type: longpoll
        options:
          request_timeout: 10
          queue_limit_bytes: 0
          queue_limit_messages: 0
          session_timeout: 1800 
```

but the effect is that the longpoll gets cancelled by the client running in the browser after 60 seconds.
I've tried to understand and read the code pertaining to the transport to see if maybe it was the doc that was outdated and the parameter was renamend to something else. What i found is that the request_timeout  is set here: https://github.com/crossbario/crossbar/blob/master/crossbar/router/longpoll.py#L620 in the WampLongPollResource initialization code but never used anywhere else in the code of the module. I don't know yet if it's read from other code or maybe  used in twisted. I see special code to kill the session after the "session_timeout", but nothing for the single request.
