### ISSUE TITLE
Security issue - information leak through "call" operations

### ISSUE THREAD

**Issue by haizaar** [crossbario/crossbar#1463]
Good day,

I have crossbar:pypy3-18.9.2 serving a realm with dynamic authorizer. For publish, subscribe and register operation attempts, request is forwarded to authorizer first and foremost (I am publishing with acks) so authorizer have a chance to return `wamp.error.not_authorized` without giving up any sensitive information.

For call operations, if no one registered for the requested procedure, `wamp.error.no_such_procedure` is returned, *without calling authorizer first*. This way a malicious client can sniff out all URIs that have a registrants behind them.

This looks like a security leak to me - I would've expected "call" operations to behave similarly to others, namely being forwarded to authorizer first.

If there is registrant behind the URI, then authorizer is called as expected, so the problem only with URIs that do not have registrants.

**Comment by haizaar** [comment]
Similar issue with "register" operation - if someone else is already registered for the URI, then `wamp.error.procedure_already_exists` before consulting with authorizer.

**Comment by meejah** [comment]
Yes, this does indeed sound like an information-disclosure problem. I agree an unauthorized client shouldn't be able to enumerate valid procedure URIs

**Comment by oberstet** [comment]
agreed: a slight information leakage that seems unnecessary. authorization before checking for existence would fix it.

**Comment by oberstet** [comment]
I've added a "bug" label, as this is security related though this "only" leaks some info - it cannot be directly exploited, since knowing the proc exists still doesn't allow to call it (as the authorizer kicks in). but of course there are other aspects. anyways. we should fix it;)

**Comment by haizaar** [comment]
I agree this is not "breach"-grade issue, but it can be exploited to obtain quite sensitive information. For example if you sell appliances that connect to a WAMP portal, then each portal user can find out how many appliances in total are available, track your sales progress, etc.

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/crossbar/pull/1467

**Comment by haizaar** [comment]
Thanks for the quick fix!
It missed 19.1.1 release though, right?

**Comment by oberstet** [comment]
yes, it missed 19.1.1. I pushed a new release that contains the fix (and a couple of others):

* https://github.com/crossbario/crossbar/tree/v19.1.2
* https://pypi.org/project/crossbar/19.1.2/
* https://snapcraft.io/crossbar

**Comment by oberstet** [comment]
crossbar 19.1.2 docker images published:

* https://hub.docker.com/r/crossbario/crossbar/tags/
* https://hub.docker.com/r/crossbario/crossbar-armhf/tags/
* https://hub.docker.com/r/crossbario/crossbar-aarch64/tags/
* https://gist.github.com/oberstet/fd28d2f3b2721aec68c1c58e2b0cdd2c

---

sorry, we still need to integrate automatic building into our CI/CD

you can build the images by doing:

```
git checkout v19.1.2
cd crossbar/docker
source versions.sh
make qemu_deps
make build
```

**Comment by haizaar** [comment]
Checked 19.1.2 and I'm afraid the issue is not fully fixed:

On cb 18.11.2:
```
2019-01-26T03:26:06 subscribe failed with wamp.error.not_authorized
2019-01-26T03:26:06 publish failed with wamp.error.not_authorized
2019-01-26T03:26:06 call failed with wamp.error.no_such_procedure
2019-01-26T03:26:06 register failed with wamp.error.not_authorized
2019-01-26T03:26:06 register existing failed with wamp.error.procedure_already_exists
```

On cb 19.1.2:
```
2019-01-26T03:27:53 subscribe failed with wamp.error.not_authorized
2019-01-26T03:27:53 publish failed with wamp.error.not_authorized
2019-01-26T03:27:53 call failed with wamp.error.not_authorized
2019-01-26T03:27:53 register failed with wamp.error.not_authorized
2019-01-26T03:27:53 register existing failed with wamp.error.procedure_already_exists
```

I.e. all works as expected in 19.1.2, except for when trying to register on URI that already has registration.

Here is my testing script:
```python
from autobahn.asyncio.component import Component, run
from autobahn.wamp.types import PublishOptions
import txaio

txaio.start_logging(level='info')
logger = txaio.make_logger()


component = Component(
    transports="ws://example.com"
    authentication={
        "ticket": {
            "ticket": "secret",
        }
    },
    is_fatal=lambda exc: True,
)

@component.on_join
async def on_join(session, details):
    uri = "foo"
    logger.info("Entering on_join")
    options = PublishOptions(exclude_me=False, acknowledge=True)
    try:
        await session.subscribe(lambda ev: None, uri)
    except Exception as e:
        logger.error("subscribe failed with %s" % e.error)

    try:
        await session.publish(uri, "foo", options=options)
    except Exception as e:
        logger.error("publish failed with %s" % e.error)

    try:
        await session.call(uri)
    except Exception as e:
        logger.error("call failed with %s" % e.error)

    try:
        await session.register(lambda x: x, uri)
    except Exception as e:
        logger.error("register failed with %s" % e.error)

    try:
        await session.register(lambda x: x, "already.registered.uri")
    except Exception as e:
        logger.error("register  existing failed with %s" % e.error)

    await session.leave()

if __name__ == "__main__":
    run([component])
```

**Comment by haizaar** [comment]
I'm not familiar with Crossbar code, but... since register needs to check whether shared registrations are enabled before returning `procedure_already_exists` may be this is a different code path (compared to `call`)

**Comment by oberstet** [comment]
the error is thrown from here https://github.com/crossbario/crossbar/blob/b96d618c10dd7c8450521221b2e2d5b10de6c2a0/crossbar/router/dealer.py#L362, which is happening _after_ authorization (`on_authorize_success`) .. mmh. can you post your node config (the permissions section of the realm/role)?

**Comment by haizaar** [comment]
Here is the crossbar config:
```yaml
$schema: https://raw.githubusercontent.com/crossbario/crossbar/master/crossbar.json
version: 2
controller:
  id: channeler
workers:
- type: router
  realms:

  # Main realm
  - name: realm
    roles:

    # Explicitly allow Medium (authorizer) to register
    - name: authorizer
      permissions:
      - uri: foo.wamp.authorize
        match: exact
        allow:
          register: true
        disclose:
          caller: true
          publisher: true

    # Dynamic authz for the rest
    - name: main
      authorizer: foo.wamp.authorize

  # Auth realm
  - name: realm-auth
    roles:
    - name: anonymous
      permissions:
      - uri: foo.wamp.authenticate
        match: exact
        allow:
          register: true
        disclose:
          caller: true
          publisher: true

  transports:

  # Main transport - requires authentication
  - type: web
    endpoint:
      type: tcp
      port: 5555
    paths:
      healthz:
        type: static
        directory: /var/lib/crossbar/health
      ws:
        type: websocket
        auth:
          ticket:
            type: dynamic
            authenticator: foo.wamp.authenticate
            authenticator-realm: realm-auth
        options:
          enable_webstatus: false
          max_frame_size: 1048576
          max_message_size: 2097152
          auto_fragment_size: 65536
          fail_by_drop: true
          open_handshake_timeout: 2500
          close_handshake_timeout: 1000
          auto_ping_interval: 10000
          auto_ping_timeout: 5000
          auto_ping_size: 4

  # Unix Domain socket - for Authenticator
  - type: rawsocket
    endpoint:
      type: unix
      path: /var/run/crossbar/crossbar.sock

  # Unix Domain socket - for Authorizer
  - type: rawsocket
    endpoint:
      type: unix
      path: /var/run/crossbar/crossbar-auth.sock
    auth:
      ticket:
        type: dynamic
        authenticator: foo.wamp.authenticate
        authenticator-realm: realm-auth

```
