### ISSUE TITLE
[UDS] Allow dynamic sock path

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1518]
I want crossbar to create my Unix Domain Socket at $HOME/deskconn.sock, currently I can't do that because crossbar doesn't try to resolve $HOME.

**Comment by om26er** [comment]
This is going to be a very simple fix, we only need to call `os.path.expandvars()` on the `path`.

**Comment by om26er** [comment]
well actually, it seems that Crossbar (currently) creates the UDS relative to the `cbdir`, so `expandvars()` won't do it.

We probably need a way to tell Crossbar to create the UDS on absolute path instead of relative, so a new flag like `absolute: true` in RawSocket's endpoint config would do it.

Something like
```
  - type: rawsocket
    endpoint:
      type: unix
      path: $HOME/deskconn.sock
      absolute: true
```
