### ISSUE TITLE
HTTP Pusher service to predefined topic

### ISSUE THREAD

**Issue by deceze** [crossbario/crossbar#258]
It'd be really handy to be able to have an HTTP Pusher act purely as an "adapter" between a plain HTTP request and a topic publish. Meaning, any plain old HTTP request to the configured URL should simply trigger a predefined publish on a predefined topic.

The specific use case I'm thinking about is an HTTP callback endpoint. Many 3rd party services offer HTTP notifications about specific events. It's not possible to control their request format, as the current HTTP Pusher requires. But these requests also do not require any particular response, so having to write a WSGI guest or separate web server is a bit of a waste. I'd really like to see something like:

```yaml
workers:
- type: router
  ...
  transports:
  - type: web
    ...
    paths:
      ...
      - callback:
        type: pusher
        realm: realm1
        role: anonymous
        topic: foo.bar.baz
```

So this:

    curl -d 'spam&eggs' http://example.com/callback

automatically results in this:

```python
publish('foo.bar.baz', 'spam&eggs')
```

Not sure if parsing the request body should be in scope for this thing or if it should simply pass along the whole request object as is, that's just the icing on the cake though.
