### ISSUE TITLE
Add a way to start Python guests using Process instead of popen

### ISSUE THREAD

**Issue by estan** [crossbario/crossbar#282]
PyCharm is one of the best Python IDEs around, and allows for debugging even into subprocesses. This makes it possible to start a debugging session for `crossbar start` and set breakpoints in guests, which is very handy.

It even has some magic so that even if you `popen` a Python interpreter, it'll modify your command line to insert the `pydev.py` debugger script. This is how it works in the context of launching `crossbar start` I think. Unfortunately this will not work if your `popen` arguments has the format `python -m ...`. That is, when you're running your script as a module.

See [this StackOverflow question](http://stackoverflow.com/questions/26465221/debugging-popen-subprocesses-with-pycharm) for more information.

The effect for me is that instead of

```yaml
  - type: guest
    executable: python2
    arguments:
      - -m
      - orexplore.simulators.mbg120
      - --device
      - .crossbar/mbg120_dev
      - --logfile
      - .crossbar/mbg120_simulator.log
    options:
      workdir: ..
```

I must use

```yaml
  - type: guest
    executable: python2
    arguments:
      - orexplore/simulators/mbg120.py
      - --device
      - .crossbar/mbg120_dev
      - --logfile
      - .crossbar/mbg120_simulator.log
    options:
      workdir: ..
      env:
        vars:
          PYTHONPATH: /home/estan/Project/orexplore/dev/Elvis/analysed
```

to launch my guest as a script instead of as a module. See the first [StackOverflow answer](http://stackoverflow.com/a/27618724/252857) (second suggested solution) for how I found this workaround.

Now, it would be nice if there was a way to get Crossbar to launch non-WAMP (but still Python) guests through the `multiprocessing.Process` mechanism, instead of through `os.popen` (which I guess it is using now for all guests?). That way, Python guests could be launched as modules and still be debuggable through PyCharm (pydev).

Consider this a low priority wish :) But would be very nice.
