### ISSUE TITLE
Ticket authentication impossible with JSON serialization and Python 3

### ISSUE THREAD

**Issue by agronholm** [crossbario/crossbar#592]
Whether or not the client session returns `bytes` or `str` from `onChallenge()` for ticket authentication, the resulting signature will always be `str` on the router if JSON serialization is used. The router, however, always encodes the ticket into bytes, resulting in a `str` vs `bytes` comparison which can never succeed.

**Comment by oberstet** [comment]
@agronholm 

We've done a lot of cleanups and py2/3 fixes and added additional asserts in the recent days.

I have just tested the following two examples

* https://github.com/crossbario/crossbarexamples/tree/master/authentication/ticket/static
* https://github.com/crossbario/crossbarexamples/tree/master/authentication/ticket/dyanmic

using trunk of txaio, autobahn and crossbar with all combinations of

* Python 2 and Python 3
* json and cbor

(all on ubuntu). Everything is working as expected now for me.

If you have the chance, please give it a shot.

**Comment by oberstet** [comment]
Also, FWIW, I have now moved to CPy 3.5.1 as my main dev env. - so I'll catch this unicode/py2/3 crazyness earlier on.

**Comment by agronholm** [comment]
I ran my test suite again with autobahn an crossbar master. Now wamp-cra works but both ticket and anonymous authentication fail due to Crossbar believing they're not configured. Here's my config.yaml:
```yaml
workers:
- type: router
  realms:
  - name: default
    roles:
    - name: authorized_users
      permissions:
      - {call: true, publish: true, register: true, subscribe: true, uri: '*'}
    - name: anonymous
      permissions:
      - {call: true, publish: true, register: true, subscribe: true, uri: '*'}
  transports:
  - type: websocket
    endpoint:
      type: tcp
      interface: localhost
      port: 56666
    auth:
      anonymous: {}
      wampcra:
        type: static
        users:
          testuser:
            secret: testpass
            role: authorized_users
      ticket:
        type: static
        principals:
          device1:
            ticket: abc123
            role: authorized_users
```
The same configuration works with wamp-cra and anonymous authentication against the latest release version of Crossbar with autobahn-master.
