### ISSUE TITLE
Use snaps as packaging format

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#900]
Please update the crossbar in the Ubuntu Store, the last one uploaded on Apr 29, 2015 and I believe that snappy is now ready for Prime time with the release of UbuntuCore 16 around the corner.

I am willing to help in anyway possible.

**Comment by oberstet** [comment]
Welcome Omer! Yeah, having Crossbar.io available on Snappy Core is definitely a goal. In particular, given Snappy's target systems like lights-out servers and IoT devices which also happens to be the focus for Crossbar.io. So your help and input is highly welcome!

One of the first questions we have to decide upon is where the Crossbar.io packaging for Snappy should live (which repo).

Because, eg for Docker we have a separate repo [here](https://github.com/crossbario/crossbar-docker). One reason is that we rather don't want to mix specific packaging with the main repo. Another one is that for contributions to Crossbar.io code itself, we need a [CAA](https://github.com/crossbario/crossbar/blob/master/CONTRIBUTING.md#send-us-a-contributor-assignment-agreement), while the above Docker repo is MIT and doesn't require any CAA or what.

We might think about renaming the Docker repo to something more general.

But anyways: this is great. I am totally positive on Snappy - I really grok the design approach taken.

@meejah @hawkowl ping ..

**Comment by oberstet** [comment]
@hawkowl I'm a moron. I totally forgot that you (once) published to snap store already in the past, right? Because we also have these docs http://crossbar.io/docs/Installation-on-Ubuntu-Snappy/

Where does it come from? I mean, do we have a snap file already somewhere (there doesn't seem to be one in the private packaging repo). And what about LP presence? Obviously, I lost oversight;)

**Comment by hawkowl** [comment]
@oberstet I have the build in the crossbarpackage repo; with the rest of the Linux packaging. I think the main issue was that I have to pass the .snaps from my builds to you, so they could get uploaded.

Next CB release I could revisit the snaps and hopefully get one we can upload to the Store :)

**Comment by oberstet** [comment]
@hawkowl ah, I see;) yeah, next release with Snappy support would be nice!

**Comment by om26er** [comment]
Hi! Seems you guys already have the snappy packaging in place, that's great to know.

One thing I would like to mention is that crossbar/controller/node.py relies on to /var/lib/dbus/machine-id get the machine's unique ID. That path is not available in the snap so this results in crossbar not starting after the first run. The fact that it runs even during the first run is a bug(tm).

This is the error I get:
om26er@X1C:~/Documents/c$ crossbar-om26er.crossbar start
2016-10-14T01:04:22+0500 [Controller   8016] Traceback (most recent call last):
2016-10-14T01:04:22+0500 [Controller   8016]   File "/snap/crossbar-om26er/3/bin/crossbar", line 11, in <module>
2016-10-14T01:04:22+0500 [Controller   8016]     load_entry_point('crossbar==16.10.dev1', 'console_scripts', 'crossbar')()
2016-10-14T01:04:22+0500 [Controller   8016]   File "/snap/crossbar-om26er/3/lib/python3.5/site-packages/crossbar/controller/cli.py", line 1023, in run
2016-10-14T01:04:22+0500 [Controller   8016]     options.func(options, reactor=reactor)
2016-10-14T01:04:22+0500 [Controller   8016]   File "/snap/crossbar-om26er/3/lib/python3.5/site-packages/crossbar/controller/cli.py", line 598, in run_command_start
2016-10-14T01:04:22+0500 [Controller   8016]     pubkey = node.maybe_generate_key(options.cbdir)
2016-10-14T01:04:22+0500 [Controller   8016]   File "/snap/crossbar-om26er/3/lib/python3.5/site-packages/crossbar/controller/node.py", line 279, in maybe_generate_key
2016-10-14T01:04:22+0500 [Controller   8016]     raise Exception("Corrupt node private key file {} - {} tag not found".format(privkey_path, tag))
2016-10-14T01:04:22+0500 [Controller   8016] Exception: Corrupt node private key file /home/om26er/Documents/c/.crossbar/key.priv - machine-id tag not found

**Comment by codegastudio** [comment]
Same as @om26er with last version of jessie on raspberry pi

**Comment by oberstet** [comment]
So one required change would be going over `crossbar/controller/node.py` and the `machine-id` determination (uses `/var/lib/dbus/machine-id` which breaks on snaps).

**Comment by om26er** [comment]
Hi! If this isn't being worked on by anyone, I'd like to take this on, in my spare time. I can start with addressing the above comment and then move to actually updating the packaging and integrating upload to the Snap store as part of the release process and finally updating the [documentation](http://crossbar.io/docs/Installation-on-Ubuntu-Snappy/)

**Comment by om26er** [comment]
Apparently the issue with /var/lib/dbus/machine-id is already addressed, not sure when that was fixed though, currently the code just returns the hostname if that path cannot be accessed. In future, for snapd' case we could talk to dbus to get the machine ID under a system running snapd, though that code would be snap specific and needs discussion if we want that.

OTH, I updated the packaging that I had done a few months ago and it seems to be working nicely. I just had to install snapcraft, the snap builder tool and run a single command and the snap was generated for me. Obviously this requires a lot of testing to be sure everything is working as expected that's why I put grade: devel.

Now the question is which repository we want to put that packaging to ?
```
name: crossbar
version: '17.5.1'
summary: Crossbar.io - Polyglot application router.
description: |
  Crossbar.io is a networking platform for distributed and microservice applications.
  It is feature rich, scalable, robust and secure. Let Crossbar.io take care of the
  hard parts of messaging so you can focus on your app's features.
grade: devel
confinement: strict

apps:
  crossbar:
    command: bin/crossbar
    plugs: [home, network, network-bind]

parts:
  crossbar:
    plugin: python
    source: https://github.com/crossbario/crossbar.git
    python-packages:
      - cffi>=1.1.0
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev
      - make
```
